import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ToDo List App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          ToDo List
        </h3>

        <div className='todo-list-table-section'>
          <table className='table table-bordered todo-list-table'>
            <thead>
              <tr>
                <th>#</th>
                <th>Task Name</th>
                <th>To be completed date</th>
                <th>Created At</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>001</td>
                <td>Buy socks</td>
                <td>27 July, 2022</td>
                <td>24 July, 2022</td>
                <td>Edit</td>
              </tr>
              <tr>
                <td>001</td>
                <td>Buy socks</td>
                <td>27 July, 2022</td>
                <td>24 July, 2022</td>
                <td>Edit</td>
              </tr>
              <tr>
                <td>001</td>
                <td>Buy socks</td>
                <td>27 July, 2022</td>
                <td>24 July, 2022</td>
                <td>Edit</td>
              </tr>
              <tr>
                <td>001</td>
                <td>Buy socks</td>
                <td>27 July, 2022</td>
                <td>24 July, 2022</td>
                <td>Edit</td>
              </tr>
              <tr>
                <td>001</td>
                <td>Buy socks</td>
                <td>27 July, 2022</td>
                <td>24 July, 2022</td>
                <td>Edit</td>
              </tr>
            </tbody>
          </table>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
